### PR TITLE
#2 Persisting the User on Page Refresh

### PR DESCRIPTION
**Pull request by Maryam-bit**

### CODE REVIEW

**Comment by Maryam-bit** [comment]
Hello,

I believe I've addressed the necessary changes in my pull request. If there are any additional improvements or modifications required, please do let me know.

Additionally, I kindly request that you consider adding the "hacktoberfest-accepted" label to my pull request, as I believe it meets the criteria for Hacktoberfest contributions.

Thank you for your time and consideration.

Best regards,
Maryam Noor

**Comment by diwash007** [comment]
Hi Maryam,
Thanks for pushing the fix. When the page is reloaded, the online user's indicator shows the wrong number.

**Comment by diwash007** [comment]
image
and also .. the user leaving message is shown when he reloads .. but is on the room without rejoining message

**Comment by pixel-pixy** [comment]
@diwash007  it's the minor issue of missing dependency in room useEffect

Adding _socket_ as dependency of `useEffect` at line 23 resolves this issue
 ```
 useEffect(() => {
    if (roomUsers[roomId]?.includes(socket?.id)) return;
    socket?.emit("send_message", {
      text: username + " joined the room.",
      socketId: "kurakani",
      roomId: roomId,
    });
    socket?.emit("join_room", roomId);
  }, [socket]);
```

Cc @Maryam-bit

**Comment by diwash007** [comment]
> git pull git@github.com:Maryam-bit/kurakani.git 2/persist-the-user-on-page-refresh

Thank you @pixel-pixy

**Comment by pixel-pixy** [comment]
@diwash007 awesome, could you add `hacktoberfest-accepted` label to the this PR I believe the author is participating in **hactoberfest**

**Comment by diwash007** [comment]
> @diwash007 awesome, could you add `hacktoberfest-accepted` label to the this PR I believe the author is participating in **hactoberfest**

sure

**Comment by Maryam-bit** [comment]
Thankyou Guys @diwash007 @pixel-pixy

**Pull request merged**
