### PR TITLE
Fixed the alignment of the button & given a new border

### PR DESCRIPTION
**Pull request by ashikjhonson**
solves: #14 

Screenshot 2023-10-14 154309

### CODE REVIEW

**Review by diwash007 — CHANGES_REQUESTED** [review]
can you please make it more rounded? matching the theme of the website
+ a little more horizontal padding

**Comment by ashikjhonson** [comment]
Alright, Have a look at the new one.

Screenshot 2023-10-14 223230

**Review by diwash007 — APPROVED** [review]
GG .. well done

**Comment by ashikjhonson** [comment]
Thanks buddy :)

**Comment by diwash007** [comment]
It will be merged. don't close it

**Comment by ashikjhonson** [comment]
Fine, closed it by mistake.

**Pull request merged**
